### ISSUE TITLE
Is there an appetite for 1.6/2.0.1 conversions?

### ISSUE THREAD

**Issue by huntc** [codelabsab/rust-ocpp#105]
Thanks for providing this crate.

I've started to play around with providing conversions between 1.6 and 2.0.1 and my initial view is that, sans some renaming, 1.6 is a subset of 2.0.1, and it is semantically compatible.

I'm sure I'll discover more as I go, but I was wondering if they'd be interest in having the conversions available from this crate.

Here's an incomplete sample conversion:

```rust
pub struct Converter<T>(pub T);

...

impl TryFrom<v2_0_1::messages::authorize::AuthorizeRequest>
    for Converter<v1_6::messages::authorize::AuthorizeRequest>
{
    type Error = Error;
    fn try_from(v: v2_0_1::messages::authorize::AuthorizeRequest) -> Result<Self, Self::Error> {
        type To = v1_6::messages::authorize::AuthorizeRequest;
        {
            Ok(Self(To {
                id_tag: TryInto::<Converter<_>>::try_into(v.id_token)?.0,
            }))
        }
    }
}
```

(there is a conversion for the `id_token` also...)

I've then declared a macro to make the above a bit easier on the eyes. The above becomes:

```rust
convert!(
    v,
    v2_0_1::messages::authorize::AuthorizeRequest,
    v1_6::messages::authorize::AuthorizeRequest,
    {
        Ok(Self(To {
            id_tag: TryInto::<Converter<_>>::try_into(v.id_token)?.0,
        }))
    }
);
```

Now, I've only converted two messages and their fields so far... this could well end up being a futile exercise. What I'm looking for is to normalise my internal model to 2.0.1 and talk 1.6 to EVSEs etc.

Am I doomed, and is there interest in these conversions being integrated here? I realise there's a degree of lossiness going from 2.0.1 to 1.6, but I think that's manageable...

**Comment by tommymalmqvist** [comment]
Hi @huntc and thank you for your suggestion and checking out this library crate.

I'm not sure the functionality should be part of this crate. I've decided to keep the lib very minimal and just focus on the types defined in the specification.

I've had many requests for implementing connectors and the like but I do not have the time, unfortunately, and will leave that up to the implementors.

It's hard to say if you are doomed or not. Of course 2.0.1 will have added types, since it's the next iteration of the specification, but there might also be changes to the types from 1.6. I cannot remember from the top of my head.

Maybe you can use the json test schemas under `src/tests/schema_validation/schemas` to check if this is possible before you dive too deep.

**Comment by huntc** [comment]
> I'm not sure the functionality should be part of this crate. I've decided to keep the lib very minimal and just focus on the types defined in the specification.

Thanks. I think it’s important to remain focused. However, I’d say that conversions could still be in line with your focus of being confined to the specification’s types. Up to you though if course. 

I’ll report back on my progress. We could also release our work separately, retaining a dependency on this crate.

**Comment by huntc** [comment]
Closing for now.
